### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by zjrwtx** [VMTask/NewBing-Prod#1]
![image](https://user-images.githubusercontent.com/86822589/231441049-9763d363-6a17-4405-b920-5631f3c55090.png)

**Comment by Nu11Const** [comment]
> ![image](https://usercontent.githubfast.com/user-images/86822589/231441049-9763d363-6a17-4405-b920-5631f3c55090.png)

Hey,vercel server function doesn't support Websocket.Deploy your own.
